### ISSUE TITLE
Change @everyone notification to @here

### ISSUE THREAD

**Issue by MadnessExpress** [z64/discord-against-humanity#9]
Changing the `@everyone` notification to `@here`, would be better in my opinion, so that offline user's don't get random notifications. I wanted to get your thoughts on this before submitting a pr for it, in case you chose `@everyone` for a specific reason.

**Comment by z64** [comment]
Ultimately it doesn't matter - because this event only occurs in the game channel, that the bot creates. All users that invited to the game can be safely assumed to be online, otherwise the game can't progress. (Why would you invite an offline user?)

Relevant code:

https://github.com/z64/discord-against-humanity/blob/master/src/modules/commands/game.rb#L15

https://github.com/z64/discord-against-humanity/blob/master/src/modules/commands/game.rb#L189

Thusly, `@here` would still accomplish the same thing, and I would accept the PR.

**Edit:** **The small oversight on my part ; administrators who will see the channel no matter what, if they are part of the game or not. So, maybe this is indeed worth doing.**

This does bring up other relevant (and somewhat roadmap) enhancements though:
1. Allow a game to be started in an _existing_ text channel.
2. Allow users to be added / removed from the game during gameplay. This is complicated, and can only occur at certain points in the game loop to prevent the game from locking up waiting for a user that can't make a play.

And other ways it could be circumvented other than `@here`
- Give players a role that can be mentioned, instead of `@here` or `@everyone`. As this would introduce additional permissions the bot would require, this isn't desirable.

**Comment by z64** [comment]
I'll note that if **Allow a game to be started in an existing text channel.** is to be added, **Allow users to be added / removed from the game during gameplay.** _must_ be added as well. If a game is going to be seen playing in a public channel, people are going to want to dynamically join / leave.

**Comment by MadnessExpress** [comment]
Yeah, I thought about maybe a way to mention specific users that were part of the game, but that isn't desirable either, because it would clutter the message, especially in large games.

I was also going to submit the enhancement for adding or removing users during a game, as we have people that have a tendency to drop out of the game, or join the game. I haven't looked much into the code yet to see what that would require, though I imagine it would be fairly complex based on how the game works.

**Comment by Cyan101** [comment]
can always make a group/tag for the players and then call them with something like @DiscordAgainstHumanity or @DAHgame etc. that would work in an open channel and only notify the players

**Comment by z64** [comment]
@FormalHellhound 

This is actually quite easy to add and remove players from the game.

``` ruby
new_player = game.add_player(discord_id: 123456, ...)
new_player.restock_hand!
new_player.dm_unplayed
```

``` ruby
player.destroy
```

is all that is required for database interactions to handle this. Destroying the player will properly clean up his cards, etc, as they are tied with an `on_delete: :cascade` option in the SQL table. I've done this before, manually, through `dah.eval`

The issue, is gating _when_ you do this, because depending on the game state, it could result in a state where the game can no longer progress. 

The only scenario I'm aware of where this would happen is when
1. All existing players have submitted a card
2. The Czar has not made their choice yet

In this state, once you add or remove a new player, things like updating the round message to include additional plays once all the plays have been revealed for the Czar to pick, and some other things won't be able to occur.

So you have to be careful about how you handle this.

The way I was going to do it, is to throw _new_ users into a queue to be added onto the _next_ round, at the beginning where we have a clean state. Something similar would have to happen for removing users, or otherwise you would have to check game state after removing a user to trigger any events for the game to progress. By this I mean, say all but ONE person has picked a card, because they have gone AFK. If you remove this person, they obviously can't issue a `play (number)` command, which would have triggered the game to advance to the next state where it waits for the Czar to pick.

Game state is something I'm handling in my next update, so I think this is best left alone until then. (Currently, the game doesn't know what state its in - the `play.rb` event evaluates this itself. It shouldn't, and won't have to do this in the future.)

@Cyan101 I mentioned this as a possibility above, but I do not want to do this, as it would impose additional permissions that the bot would require for no real reason when `@here` would suffice. I would like to keep the bot as permission-lean and permission-flexible as possible.

**Comment by z64** [comment]
Anyway, this issue is getting off-topic. 

@FormalHellhound If you would like to change it to `@here`, that's fine :+1: 
If not I will probably end up doing so myself.
